<?php

class INTERN_REAL_DATA
{
    private static $province = [
        [10,'กรุงเทพมหานคร','Bangkok',2],
        [11,'สมุทรปราการ','Samut Prakan',2],
        [12,'นนทบุรี','Nonthaburi',2],
        [13,'ปทุมธานี','PathumThani',2],
        [14,'พระนครศรีอยุธยา','PhraNakhonSiAyutthaya',2],
        [15,'อ่างทอง','AngThong',2],
        [16,'ลพบุรี','Loburi',2],
        [17,'สิงห์บุรี','SingBuri',2],
        [18,'ชัยนาท','ChaiNat',2],
        [19,'สระบุรี','Saraburi',2],
        [20,'ชลบุรี','ChonBuri',5],
        [21,'ระยอง','Rayong',5],
        [22,'จันทบุรี','Chanthaburi',5],
        [23,'ตราด','Trat',5],
        [24,'ฉะเชิงเทรา','Chachoengsao',5],
        [25,'ปราจีนบุรี','PrachinBuri',5],
        [26,'นครนายก','NakhonNayok',2],
        [27,'สระแก้ว','SaKaeo',5],
        [28,'นครราชสีมา','NakhonRatchasima',3],
        [29,'บุรีรัมย์','BuriRam',3],
        [30,'สุรินทร์','Surin',3],
        [31,'ศรีสะเกษ','SiSaKet',3],
        [32,'อุบลราชธานี','UbonRatchathani',3],
        [33,'ยโสธร','Yasothon',3],
        [34,'ชัยภูมิ','Chaiyaphum',3],
        [35,'อำนาจเจริญ','AmnatCharoen',3],
        [36,'หนองบัวลำภู','NongBuaLamPhu',3],
        [37,'ขอนแก่น','KhonKaen',3],
        [38,'อุดรธานี','UdonThani',3],
        [39,'เลย','Loei',3],
        [40,'หนองคาย','NongKhai',3],
        [41,'มหาสารคาม','MahaSarakham',3],
        [42,'ร้อยเอ็ด','RoiEt',3],
        [43,'กาฬสินธุ์','Kalasin',3],
        [44,'สกลนคร','SakonNakhon',3],
        [45,'นครพนม','NakhonPhanom',3],
        [46,'มุกดาหาร','Mukdahan',3],
        [47,'เชียงใหม่','ChiangMai',1],
        [48,'ลำพูน','Lamphun',1],
        [49,'ลำปาง','Lampang',1],
        [50,'อุตรดิตถ์','Uttaradit',1],
        [51,'แพร่','Phrae',1],
        [52,'น่าน','Nan',1],
        [53,'พะเยา','Phayao',1],
        [54,'เชียงราย','ChiangRai',1],
        [55,'แม่ฮ่องสอน','MaeHongSon',1],
        [56,'นครสวรรค์','NakhonSawan',2],
        [57,'อุทัยธานี','UthaiThani',2],
        [58,'กำแพงเพชร','KamphaengPhet',2],
        [59,'ตาก','Tak',4],
        [60,'สุโขทัย','Sukhothai',2],
        [61,'พิษณุโลก','Phitsanulok',2],
        [62,'พิจิตร','Phichit',2],
        [63,'เพชรบูรณ์','Phetchabun',2],
        [64,'ราชบุรี','Ratchaburi',4],
        [65,'กาญจนบุรี','Kanchanaburi',4],
        [66,'สุพรรณบุรี','SuphanBuri',2],
        [67,'นครปฐม','NakhonPathom',2],
        [68,'สมุทรสาคร','SamutSakhon',2],
        [69,'สมุทรสงคราม','SamutSongkhram',2],
        [70,'เพชรบุรี','Phetchaburi',4],
        [71,'ประจวบคีรีขันธ์','PrachuapKhiriKhan',4],
        [72,'นครศรีธรรมราช','NakhonSiThammarat',6],
        [73,'กระบี่','Krabi',6],
        [74,'พังงา','Phangnga',6],
        [75,'ภูเก็ต','Phuket',6],
        [76,'สุราษฎร์ธานี','SuratThani',6],
        [77,'ระนอง','Ranong',6],
        [78,'ชุมพร','Chumphon',6],
        [79,'สงขลา','Songkhla',6],
        [80,'สตูล','Satun',6],
        [81,'ตรัง','Trang',6],
        [82,'พัทลุง','Phatthalung',6],
        [83,'ปัตตานี','Pattani',6],
        [84,'ยะลา','Yala',6],
        [85,'นราธิวาส','Narathiwat',6],
        [86,'บึงกาฬ','buogkan',3],
    ];

    public static $skills = [
        'Design / Creative' => [
            '3D animation',
            '3D rendering',
            'Adobe photoshop',
            'Adobe illustrator',
            'Adobe indesign',
            'Adobe Dreamweaver',
            'After Effects',
            'Architecture',
            'Brain Storming',
            'Branding',
            'Copy Editing',
            'Copywriting',
            'Creative Presentation',
            'Email Marketing/Newsletters',
            'Facebook Marketing',
            'Fashion Design',
            'Final Cut Pro',
            'Flash',
            'Furniture Design',
            'Google Adsense',
            'Google Adwords',
            'Handcrafts',
            'Industrial Design',
            'Market Research',
            'Material Design',
            'Maya',
            'Packaging Design',
            'Photo Editing',
            'Publishing',
            'Social Media Management',
            'Typography',
            'Video Broadcasting',
            'Video Editing',
            'Videography',
            'Viral Marketing',
        ],
        'IT' => [
            'Android',
            'ASP.NET',
            'Apache',
            'C',
            'C#',
            'C++',
            'Computer Graphics',
            'CSS',
            'Data Warehousing',
            'Database Development',
            'eCommerce',
            'Google Chrome',
            'HTML 5',
            'Javascript',
            'Java',
            'Mac OS',
            'Microsoft Access',
            'Microsoft office',
            'Microsoft SQL Server',
            'Mysql',
            '.NET',
            'Oracle',
            'PHP',
            'SQL',
            'Social media',
            'VB.NET',
            'VMware',
            'Visual Basic',
            'Twitter',
            'Wordpress',
            'Windows Server',
            'Windows API',
            'XML',
            'YouTube',
        ],
        'General Skills' => [
            'Analytical Thinking',
            'Creative Writing',
            'Diplomacy',
            'Energetic',
            'Enthusiastic',
            'Fast Learner',
            'Good communication Skills',
            'High Responsibilities',
            'Leadership Skills',
            'Meet Deadlines',
            'Multitasking',
            'News Reporting',
            'Outgoing Personality',
            'Pleasant Personality',
            'Positive Thinker',
            'Problem Solving',
            'Producing Reports',
            'Public Speaking',
            'Punctual',
            'Service-Minded',
            'Teaching',
            'Teamwork',
            'willing to work overtime',
            'work well under pressure',
        ],
        'Business' => [
            'Business Statistics/Analysis',
            'Contracts',
            'Corporate Law',
            'Event Planning',
            'Excel & Data Entry',
            'Human Resource Management',
            'Inventory / Warehouse Management',
            'Management',
            'Market Analysis',
            'Negotiation',
            'Payroll',
            'Procurement',
            'Project Management',
            'Property Management / Development',
            'Public Relations',
            'Recruitment',
            'Sales',
        ],
        'Engineering' => [
            'Automation',
            'Biology',
            'CAD',
            'Civil Engineering',
            'Construction Monitoring',
            'Electronics',
            'Geolocation',
            'Instrument',
            'Mechanical',
            'Quality Management System',
            'SAP System',
            'Statistics',
            'Chemical',
        ],
        'Finance' => [
            'Accounting',
            'Assurance',
            'Budgeting',
            'CAESAR',
            'Cash Flow Management',
            'CFA ',
            'CFP ',
            'Cost Analysis',
            'Derivative License',
            'Finance',
            'Financial Modeling',
            'IC License',
            'IP License',
            'M&A',
            'Quantitative Analysis',
            'Risk Management',
            'Single License',
            'Taxation',
            'Valuation Techniques',
        ],
        'Job Objective' => [
            'Ability to travel upcountry',
            'Attend Workshops (Industry specific)',
            'Industry trends',
            'Own Transportation and Driving Licence',
            'Personal networks',
            'Professional publication'
        ],
        'Science' => [
            'BRC Global Standard',
            'Certification',
            'Chemical Processing',
            'EHS Management',
            'GMP',
            'HACCP',
            'ISO/ TS16949',
            'ISO 14001',
            'ISO 15189:2008',
            'ISO 18001',
            'ISO 9001',
            'Laboratory equipment calibration',
            'Laboratory instruments expertise',
            'Neuroscience',
            'Nutricion',
            'OHSAS 18001',
            'Petrochemical',
            'Product Development',
            'Product Testing',
            'Quality Assurance',
            'Research',
            'Safety Management',
        ],
    ];

    private static $university = [
        ['มหาวิทยาลัยกาฬสินธุ์','Rajabhat Galasin','KSU','มสก.','http://www.ksu.ac.th/',43],
        ['มหาวิทยาลัยนครพนม','Nakorn panom','NPU','มนพ.','http://www.npu.ac.th/',45],
        ['จุฬาลงกรณ์มหาวิทยาลัย','Jula longorn','CU','จุฬาฯ','http://www.chula.ac.th/',10],
        ['มหาวิทยาลัยธรรมศาสตร์','tamasas','TU','มธ.','http://www.tu.ac.th/',10],
//        ['มหาวิทยาลัยเกษตรศาสตร์','ggg'],
//        ['มหาวิทยาลัยมหิดล'],
//        ['มหาวิทยาลัยศิลปากร'],
//        ['มหาวิทยาลัยเชียงใหม่'],
//        ['มหาวิทยาลัยขอนแก่น'],
//        ['มหาวิทยาลัยสงขลานครินทร์'],
//        ['มหาวิทยาลัยรามคำแหง'],
//        ['สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง'],
//        ['มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ'],
//        ['มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี'],
//        ['มหาวิทยาลัยศรีนครินทรวิโรฒ'],
//        ['มหาวิทยาลัยสุโขทัยธรรมาธิราช'],
//        ['มหาวิทยาลัยเทคโนโลยีสุรนารี'],
//        ['มหาวิทยาลัยนเรศวร'],
//        ['มหาวิทยาลัยอุบลราชธานี'],
//        ['มหาวิทยาลัยบูรพา'],
//        ['มหาวิทยาลัยวลัยลักษณ์'],
//        ['มหาวิทยาลัยทักษิณ'],
//        ['มหาวิทยาลัยแม่โจ้'],
//        ['มหาวิทยาลัยแม่ฟ้าหลวง'],
//        ['มหาวิทยาลัยนราธิวาสราชนครินทร์'],
//        ['มหาวิทยาลัยนครพนม'],
//        ['มหาวิทยาลัยพะเยา'],
//        ['มหาวิทยาลัยสวนดุสิต'],
//        ['มหาวิทยาลัยกรุงเทพ'],
//        ['มหาวิทยาลัยกรุงเทพธนบุรี'],
//        ['มหาวิทยาลัยกรุงเทพสุวรรณภูมิ'],
//        ['มหาวิทยาลัยการจัดการและเทคโนโลยีอีสเทิร์น'],
//        ['มหาวิทยาลัยเกริก'],
//        ['มหาวิทยาลัยเกษมบัณฑิต'],
//        ['มหาวิทยาลัยคริสเตียน'],
//        ['มหาวิทยาลัยเฉลิมกาญจนา'],
//        ['มหาวิทยาลัยตาปี'],
//        ['มหาวิทยาลัยเจ้าพระยา'],
//        ['มหาวิทยาลัยชินวัตร'],
//        ['มหาวิทยาลัยเซนต์จอห์น'],
//        ['มหาวิทยาลัยเทคโนโลยีมหานคร'],
//        ['มหาวิทยาลัยธุรกิจบัณฑิตย์'],
//        ['มหาวิทยาลัยธนบุรี'],
//        ['มหาวิทยาลัยนอร์ทกรุงเทพ'],
//        ['มหาวิทยาลัยนอร์ท-เชียงใหม่'],
//        ['มหาวิทยาลัยนานาชาติแสตมฟอร์ด'],
//        ['มหาวิทยาลัยนานาชาติเอเชีย-แปซิฟิก'],
//        ['มหาวิทยาลัยเนชั่น'],
//        ['มหาวิทยาลัยปทุมธานี'],
//        ['มหาวิทยาลัยพายัพ'],
//        ['มหาวิทยาลัยพิษณุโลก'],
//        ['มหาวิทยาลัยฟาร์อีสเทอร์น'],
//        ['มหาวิทยาลัยภาคกลาง'],
//        ['มหาวิทยาลัยรังสิต'],
//        ['มหาวิทยาลัยราชธานี'],
//        ['มหาวิทยาลัยรัตนบัณฑิต'],
//        ['มหาวิทยาลัยภาคตะวันออกเฉียงเหนือ'],
//        ['มหาวิทยาลัยราชพฤกษ์'],
//        ['มหาวิทยาลัยวงษ์ชวลิตกุล'],
//        ['มหาวิทยาลัยเวบสเตอร์(ประเทศไทย)'],
//        ['มหาวิทยาลัยเวสเทิร์น'],
//        ['มหาวิทยาลัยศรีปทุม'],
//        ['มหาวิทยาลัยสยาม'],
//        ['มหาวิทยาลัยหอการค้าไทย'],
//        ['มหาวิทยาลัยหัวเฉียวเฉลิมพระเกียรติ'],
//        ['มหาวิทยาลัยหาดใหญ่'],
//        ['มหาวิทยาลัยอัสสัมชัญ'],
//        ['มหาวิทยาลัยฟาฏอนี'],
//        ['มหาวิทยาลัยอีสเทิร์นเอเชีย'],
//        ['มหาวิทยาลัยเอเชียน'],
//        ['มหาวิทยาลัยเอเชียอาคเนย์'],
//        ['มหาวิทยาลัยราชภัฏกาญจนบุรี'],
//        ['มหาวิทยาลัยราชภัฏกำแพงเพชร'],
//        ['มหาวิทยาลัยราชภัฏจันทรเกษม'],
//        ['มหาวิทยาลัยราชภัฏชัยภูมิ'],
//        ['มหาวิทยาลัยราชภัฏเชียงราย'],
//        ['มหาวิทยาลัยราชภัฏเชียงใหม่'],
//        ['มหาวิทยาลัยราชภัฏเทพสตรี'],
//        ['มหาวิทยาลัยราชภัฏธนบุรี'],
//        ['มหาวิทยาลัยราชภัฏนครปฐม'],
//        ['มหาวิทยาลัยราชภัฏนครราชสีมา'],
//        ['มหาวิทยาลัยราชภัฏนครศรีธรรมราช'],
//        ['มหาวิทยาลัยราชภัฏนครสวรรค์'],
//        ['มหาวิทยาลัยราชภัฏบ้านสมเด็จเจ้าพระยา'],
//        ['มหาวิทยาลัยราชภัฏบุรีรัมย์'],
//        ['มหาวิทยาลัยราชภัฏพระนคร'],
//        ['มหาวิทยาลัยราชภัฏพระนครศรีอยุธยา'],
//        ['มหาวิทยาลัยราชภัฏพิบูลสงคราม'],
//        ['มหาวิทยาลัยราชภัฏเพชรบุรี'],
//        ['มหาวิทยาลัยราชภัฏเพชรบูรณ์'],
//        ['มหาวิทยาลัยราชภัฏภูเก็ต'],
//        ['มหาวิทยาลัยราชภัฏมหาสารคาม'],
//        ['มหาวิทยาลัยราชภัฏยะลา'],
//        ['มหาวิทยาลัยราชภัฏร้อยเอ็ด'],
//        ['มหาวิทยาลัยราชภัฏราชนครินทร์'],
//        ['มหาวิทยาลัยราชภัฏรำไพพรรณี'],
//        ['มหาวิทยาลัยราชภัฏลำปาง'],
//        ['มหาวิทยาลัยราชภัฏเลย'],
//        ['มหาวิทยาลัยราชภัฏวไลยอลงกรณ์ในพระบรมราชูปถัมภ์'],
//        ['มหาวิทยาลัยราชภัฏศรีสะเกษ'],
//        ['มหาวิทยาลัยราชภัฏสกลนคร'],
//        ['มหาวิทยาลัยราชภัฏสงขลา'],
//        ['มหาวิทยาลัยราชภัฏสวนสุนันทา'],
//        ['มหาวิทยาลัยราชภัฏสุราษฎร์ธานี'],
//        ['มหาวิทยาลัยราชภัฏสุรินทร์'],
//        ['มหาวิทยาลัยราชภัฏหมู่บ้านจอมบึง'],
//        ['มหาวิทยาลัยราชภัฏอุดรธานี'],
//        ['มหาวิทยาลัยราชภัฏอุตรดิตถ์'],
//        ['มหาวิทยาลัยราชภัฏอุบลราชธานี'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลกรุงเทพ'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลตะวันออก'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลธัญบุรี'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลพระนคร'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลรัตนโกสินทร์'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลศรีวิชัย'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลสุวรรณภูมิ'],
//        ['มหาวิทยาลัยเทคโนโลยีราชมงคลอีสาน'],
//        ['มหาวิทยาลัยมหาสารคาม'],
    ];

    public static function insertProvince($purge = true)
    {
        try {
            //จังหวัด
            purgeTable(INTERN_TABLE::PROVINCE);
            $province = new MODEL_Province();
            foreach (self::$province as $prov) {
                $province->setProvinceId($prov[0]);
                $province->setName($prov[1]);
                $province->setNameEng($prov[2]);
                $province->setGeoId($prov[3]);
                if(!$province->insert()) return false;
            }
            return true;
        }
        catch (Exception $e) {
            return false;
        }
    }
    public static function insertUniversity()
    {
        try {
            //มหาลัย
            purgeTable(INTERN_TABLE::UNIVERSITY);
            $university = new MODEL_University();
            $index = 0;
            foreach (self::$university as $uni) {
                $university->setUniversityId($index);
                $university->setName($uni[0]);
                $university->setNameEng($uni[1]);
                $university->setShortNameEng($uni[2]);
                $university->setShortName($uni[3]);
                $university->setWebsite($uni[4]);
                $university->setProvinceId($uni[5]);
                $index++;
                if (!$university->insert()) return false;
            }
            return true;
        }  catch (Exception $e) {
            return false;
        }
    }
    public static function insertSkillType()
    {
        try {
            //ความสามารถ
            purgeTable(INTERN_TABLE::SKILL_TYPE);

//            //ความสามารถ
//            $skillType = new MODEL_SkillType();
//            foreach (self::$skills as $key => $val) :
//                $skillType->setName($key);
//            endforeach;

            return true;
        }  catch (Exception $e) {
            return false;
        }
    }
}
